### PR TITLE
chore [NAB-49]: Update dependencies

### PR DESCRIPTION
**Pull request by pgerke**

### CODE REVIEW

**Comment by pgerke** [comment]
@michix99 👋

**Comment by michix99** [comment]
@pgerke Sorry for the delay... 👋🏻🤗

**Review by michix99 — APPROVED** [review]

**Comment by pgerke** [comment]
@michix99 no problem, just saying hello! 😉

**Comment by michix99** [comment]
@pgerke Hi 😉🙋🏻‍♀️

**Pull request merged**
